-- MySQL Script generated by MySQL Workbench
-- Wed Nov  4 11:54:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Quiz2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Quiz2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quiz2` DEFAULT CHARACTER SET utf8 ;
USE `quiz2` ;

-- -----------------------------------------------------
-- Table `Quiz2`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiz2`.`Department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `departmentCode` VARCHAR(4) NULL,
  `departmentDecripton` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `departmentCode_UNIQUE` (`departmentCode` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quiz2`.`majors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiz2`.`majors` (
  `majorsID` INT NOT NULL AUTO_INCREMENT,
  `majorCode` VARCHAR(4) NULL,
  `description` VARCHAR(45) NULL,
  `Department_id` INT NOT NULL,
  PRIMARY KEY (`majorsID`),
  UNIQUE INDEX `majorCode_UNIQUE` (`majorCode` ASC) ,
  INDEX `fk_majors_Department1_idx` (`Department_id` ASC) ,
  CONSTRAINT `fk_majors_Department1`
    FOREIGN KEY (`Department_id`)
    REFERENCES `Quiz2`.`Department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quiz2`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiz2`.`Students` (
  `studentID` CHAR(7) NULL,
  `FirstName` VARCHAR(20) NULL,
  `LastName` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `Gender` ENUM('M', 'F') NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  `majors_majorsID` INT NOT NULL DEFAULT 0,
  `totalCredits` INT NULL DEFAULT 0,
  UNIQUE INDEX `studentID_UNIQUE` (`studentID` ASC) ,
  PRIMARY KEY (`ID`),
  INDEX `fk_Students_majors_idx` (`majors_majorsID` ASC) ,
  CONSTRAINT `fk_Students_majors`
    FOREIGN KEY (`majors_majorsID`)
    REFERENCES `Quiz2`.`majors` (`majorsID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quiz2`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiz2`.`Courses` (
  `courseID` INT NOT NULL AUTO_INCREMENT,
  `courseNumber` VARCHAR(8) NULL,
  `year` INT NULL,
  `semester` VARCHAR(45) NULL,
  `majors_majorsID` INT NOT NULL,
  `courseCredits` INT NULL,
  `courseTitle` VARCHAR(45) NULL,
  PRIMARY KEY (`courseID`),
  INDEX `fk_Courses_majors1_idx` (`majors_majorsID` ASC) ,
  CONSTRAINT `fk_Courses_majors1`
    FOREIGN KEY (`majors_majorsID`)
    REFERENCES `Quiz2`.`majors` (`majorsID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quiz2`.`StudentRegistrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiz2`.`StudentRegistrations` (
  `registrationID` INT NOT NULL AUTO_INCREMENT,
  `Students_ID` INT NOT NULL,
  `Courses_courseID` INT NOT NULL,
  `LetterGrade` CHAR(1) NULL,
  `NumberGrade` DECIMAL(10,2) NULL DEFAULT 0.00,
  PRIMARY KEY (`registrationID`),
  INDEX `fk_StudentRegistrations_Students1_idx` (`Students_ID` ASC) ,
  INDEX `fk_StudentRegistrations_Courses1_idx` (`Courses_courseID` ASC) ,
  CONSTRAINT `fk_StudentRegistrations_Students1`
    FOREIGN KEY (`Students_ID`)
    REFERENCES `Quiz2`.`Students` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudentRegistrations_Courses1`
    FOREIGN KEY (`Courses_courseID`)
    REFERENCES `Quiz2`.`Courses` (`courseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quiz2`.`studentCredentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiz2`.`studentCredentials` (
  `credentialsID` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NULL,
  `password` BLOB NULL,
  `Students_ID` INT NOT NULL,
  PRIMARY KEY (`credentialsID`, `Students_ID`),
  INDEX `fk_studentCredentials_Students1_idx` (`Students_ID` ASC) ,
  CONSTRAINT `fk_studentCredentials_Students1`
    FOREIGN KEY (`Students_ID`)
    REFERENCES `Quiz2`.`Students` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
